### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by ryssbowh** [marionnewlevant/craft-snitch#25]
Hi,

An issue arises from time to time with this plugin :

```
TypeError: marionnewlevant\snitch\services\Collision::register(): Argument #2 ($snitchType) must be of type string, null given, called in /home/pkclimate/public_html/vendor/marionnewlevant/snitch/src/controllers/CollisionController.php on line 83
#10 /home/pkclimate/public_html/vendor/marionnewlevant/snitch/src/services/Collision.php(70): marionnewlevant\snitch\services\Collision::register
#9 /home/pkclimate/public_html/vendor/marionnewlevant/snitch/src/controllers/CollisionController.php(83): marionnewlevant\snitch\controllers\CollisionController::actionAjaxEnter
#8 [internal](0): call_user_func_array
#7 /home/pkclimate/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#6 /home/pkclimate/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#5 /home/pkclimate/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#4 /home/pkclimate/public_html/vendor/craftcms/cms/src/web/Application.php(293): craft\web\Application::runAction
#3 /home/pkclimate/public_html/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application::_processActionRequest
#2 /home/pkclimate/public_html/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application::handleRequest
#1 /home/pkclimate/public_html/vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 /index.php(22): null
```

Craft 3.7.43

**Comment by kringkaste** [comment]
We stumbled across this in our modifications for Craft 4 as well. It's because of php 8.
